/* Separate archive: never modifies existing revenue amounts or their schema. */
(function(){
 'use strict';
 const C=ProductionCore,DB='gr-production-archive-v1',TABLE='omzet_documents',BUCKET='omzet-bonnen';
 let docs=[],active=null,busy=false,account=null,syncing=false;
 const el=id=>document.getElementById(id),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const section=document.createElement('section');section.className='card';section.innerHTML=`<h2>4. Bonarchief en productie</h2><div class="body">
 <p>Bewaar originele PDF-bonnen en controleer de uitgevoerde hoeveelheden. Omzet en productie worden afzonderlijk bijgehouden. Orders en onbevestigde aantallen tellen niet mee.</p>
 <div class="toolbar"><button id="prodImport">Bonnen toevoegen / oude bonnen aanvullen</button><input id="prodFiles" type="file" multiple accept="application/pdf,.pdf"><button id="prodBackup" class="secondary">Archiefback-up downloaden</button><button id="prodRestore" class="secondary">Back-up herstellen</button><input type="file" id="prodRestoreFile" accept=".json"><button id="prodExport" class="secondary">Aantallen naar Excel</button></div>
 <p id="prodStatus" role="status"></p><p class="muted">Zonder cloudverbinding: alleen bewaard in deze browser. Download een back-up; browsergegevens wissen kan het lokale archief verwijderen. Oude omzetregels bevatten nog geen bonnen of aantallen.</p>
 <details><summary>Beveiligde cloud voor het bonarchief</summary><p id="prodCloudStatus">Nog niet verbonden. Het bestaande omzetoverzicht blijft ongewijzigd werken.</p><div class="toolbar"><input id="prodEmail" type="email" placeholder="Beheerdersmailadres" autocomplete="username"><input id="prodPassword" type="password" placeholder="Wachtwoord" autocomplete="current-password"><button id="prodLogin">Inloggen</button><button id="prodSync" class="secondary">Archief synchroniseren</button><button id="prodLogout" class="secondary">Uitloggen</button></div><p class="muted">Alleen aangewezen beheerders hebben toegang. Bij eerste gebruik moet de bonarchief-database zijn ingericht en een beheerdersaccount beschikbaar zijn.</p></details>
 <div class="filters" style="margin-top:18px"><label>Uitvoeringsjaar<input id="prodYear" type="number" min="2000" max="2100"></label><label>Klant<select id="prodClient"><option value="">Alle klanten</option></select></label></div>
 <div id="prodTotals" class="stats"></div><p id="prodCoverage" class="muted"></p><div id="prodDocs" class="wrap"></div>
 <div id="prodEditor" hidden style="border-top:2px solid #d9e4d4;margin-top:20px;padding-top:12px"><h3 id="prodTitle"></h3><p>Neem de uitvoeringsdatum over van de bon, niet automatisch de factuurdatum. Bij ontbreken: navragen en nog niet meetellen. Negatieve aantallen alleen voor een gecontroleerde correctie.</p><div class="toolbar"><button id="prodOpen" class="secondary">Originele PDF openen</button><button id="prodAdd" class="secondary">Regel toevoegen</button></div><div id="prodItems" class="wrap"></div><label><input id="prodExecuted" type="checkbox"> Ik heb gecontroleerd dat deze hoeveelheden uitgevoerd/gebruikt zijn en niet al via een andere bon meetellen.</label><div class="toolbar"><button id="prodDraft" class="secondary">Concept bewaren</button><button id="prodConfirm">Gecontroleerd opslaan en meetellen</button><button id="prodExclude" class="secondary">Bon uitsluiten van telling</button><button id="prodClose" class="secondary">Sluiten</button></div><details><summary>Uitgelezen brontekst (controlehulp)</summary><pre id="prodText" style="white-space:pre-wrap;max-height:300px;overflow:auto"></pre></details></div></div>`;
 document.querySelector('main').appendChild(section);el('prodYear').value=new Date().getFullYear();
 function status(t){el('prodStatus').textContent=t;}
 const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('docs',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 async function db(mode,fn){const d=await dbp;return new Promise((resolve,reject)=>{const tx=d.transaction('docs',mode),r=fn(tx.objectStore('docs'));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Opslaan afgebroken'));});}
 async function put(d){await db('readwrite',s=>s.put(d));const i=docs.findIndex(x=>x.id===d.id);if(i<0)docs.push(d);else docs[i]=d;}
 function meta(d){const {pdf,...m}=d;return m;}
 function draw(){const selected=el('prodClient').value,clients=[...new Set(docs.flatMap(d=>d.items.map(x=>x.client)).filter(Boolean))].sort();el('prodClient').innerHTML='<option value="">Alle klanten</option>'+clients.map(c=>`<option value="${safe(c)}">${safe(c)}</option>`).join('');el('prodClient').value=clients.includes(selected)?selected:'';
 const t=C.totals(docs,el('prodYear').value,el('prodClient').value);el('prodTotals').innerHTML=Object.entries(t.sums).map(([k,v])=>`<div class="stat"><b>${v.toLocaleString('nl-NL')} ${safe(k.split('|')[1])}</b><span>${safe(k.split('|')[0])}</span></div>`).join('')||'<p>Nog geen gecontroleerde aantallen in deze selectie.</p>';
 el('prodCoverage').textContent=`${t.checked} gecontroleerde bonnen; ${t.pending} bonnen nog te controleren. Dit overzicht is alleen volledig als alle relevante bonnen zijn toegevoegd. Meerdere verschillende bonnen van hetzelfde werk kunnen elkaar overlappen: controleer dit voor het meetellen.`;
 el('prodDocs').innerHTML='<table><thead><tr><th>Bon</th><th>Status</th><th>Bewaring</th><th></th></tr></thead><tbody>'+docs.map(d=>`<tr><td>${safe(d.name)}</td><td>${d.excluded?'Uitgesloten':d.confirmed?'Gecontroleerd':'Controle nodig'}</td><td>${d.dirty?'Lokaal; nog niet in cloud':'Cloud en/of lokaal'}</td><td><button data-prod-edit="${d.id}">Bekijken / aantallen</button></td></tr>`).join('')+'</tbody></table>';
 }
 async function pdfPages(file){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let p=1;p<=pdf.numPages;p++){const c=await (await pdf.getPage(p)).getTextContent();const lines=[];let y=null,line=[];for(const x of c.items){if(y!==null&&Math.abs(x.transform[5]-y)>3){lines.push(line.join(' '));line=[];}y=x.transform[5];line.push(x.str);if(x.hasEOL){lines.push(line.join(' '));line=[];y=null;}}if(line.length)lines.push(line.join(' '));pages.push(lines.join('\n'));}await pdf.destroy();return pages;}
 async function hash(buf){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',buf))].map(x=>x.toString(16).padStart(2,'0')).join('');}
 async function archive(file){await loaded;if(file.size>50*1024*1024)throw Error('Bon is groter dan 50 MB. Splits de PDF.');const buf=await file.arrayBuffer();if(!new TextDecoder().decode(buf.slice(0,1024)).includes('%PDF-'))throw Error('Dit bestand is geen PDF.');const id=await hash(buf);if(docs.some(d=>d.id===id)){status(file.name+': al in archief, niet dubbel toegevoegd.');return false;}const pages=await pdfPages(file),items=C.suggestions(pages);const d={id,name:file.name,items,pages,pdf:new Blob([buf],{type:'application/pdf'}),confirmed:false,executed:false,excluded:false,revision:0,dirty:true,updated:new Date().toISOString()};await put(d);status(file.name+': lokaal bewaard; '+items.length+' suggesties. Controleer datum, klant, project, eenheid en hoeveelheid.');draw();return true;}
 function empty(){return {project:'',client:'',date:'',kind:'Peilbuizen geplaatst',unit:'st',quantity:'',source:'Handmatig toegevoegd; controleer originele bon'};}
 function edit(id){active=structuredClone(docs.find(x=>x.id===id));el('prodEditor').hidden=false;el('prodTitle').textContent=active.name;el('prodExecuted').checked=active.executed;el('prodText').textContent=active.pages.map((p,i)=>'PAGINA '+(i+1)+'\n'+p).join('\n\n');itemsDraw();el('prodEditor').scrollIntoView({behavior:'smooth'});}
 function itemsDraw(){el('prodItems').innerHTML='<table><thead><tr><th>Uitvoering</th><th>Klant</th><th>Project</th><th>Soort</th><th>Aantal</th><th>Eenheid</th><th>Bronregel</th><th></th></tr></thead><tbody>'+active.items.map((x,i)=>`<tr>${['date','client','project','kind','quantity','unit'].map(k=>`<td>${k==='unit'?`<select data-pi="${i}" data-pk="unit">${['m','st','kg','uur','m3'].map(u=>`<option ${x.unit===u?'selected':''}>${u}</option>`).join('')}</select>`:`<input class="cell" style="min-width:${k==='kind'?170:115}px" ${k==='kind'?'list="prodKinds"':''} type="${k==='date'?'date':'text'}" data-pi="${i}" data-pk="${k}" value="${safe(x[k])}">`}</td>`).join('')}<td style="min-width:220px">${safe(x.source)}</td><td><button data-prod-remove="${i}" class="secondary">Weg</button></td></tr>`).join('')+'</tbody></table><datalist id="prodKinds">'+Object.keys(C.kinds).map(k=>`<option value="${safe(k)}">`).join('')+'</datalist>';}
 async function save(confirmed,excluded=false){if(!active)return;active.executed=el('prodExecuted').checked;if(confirmed){const e=C.errors(active);if(e.length){alert(e.join('\n'));return;}}active.confirmed=confirmed;active.excluded=excluded;active.dirty=true;active.updated=new Date().toISOString();await put(active);draw();status(confirmed?'Gecontroleerd en lokaal opgeslagen.':'Lokaal opgeslagen.');if(account){await sync();active=structuredClone(docs.find(d=>d.id===active.id));}}
 async function sync(){if(syncing)throw Error('Synchronisatie loopt al. Probeer het zo opnieuw.');syncing=true;try{await loaded;return await syncInternal();}finally{syncing=false;}}
 async function syncInternal(){if(!sb)throw Error('Cloudbibliotheek nog niet beschikbaar.');const {data:s,error:se}=await sb.auth.getSession();if(se)throw se;account=s.session?.user;if(!account)throw Error('Log eerst in voor het beveiligde bonarchief.');el('prodCloudStatus').textContent='Synchroniseren…';
 for(const d of docs.filter(x=>x.dirty)){const {data:remote,error:re}=await sb.from(TABLE).select('revision').eq('id',d.id).maybeSingle();if(re)throw re;if((remote?.revision||0)!==(d.revision||0))throw Error('Deze bon is op een ander apparaat gewijzigd: '+d.name+'. Je lokale wijziging blijft bewaard. Herstel het verschil voordat je verder synchroniseert.');if(!remote){const up=await sb.storage.from(BUCKET).upload(d.id+'.pdf',d.pdf,{contentType:'application/pdf',upsert:false});if(up.error&&String(up.error.statusCode)!=='409')throw up.error;}
 const revision=(d.revision||0)+1,payload={id:d.id,metadata:meta({...d,dirty:false,revision}),revision};const q=remote?sb.from(TABLE).update(payload).eq('id',d.id).eq('revision',d.revision):sb.from(TABLE).insert(payload);const result=await q.select('id');if(result.error)throw result.error;if(!result.data?.length)throw Error('Gelijktijdige wijziging; niets overschreven.');await put({...d,dirty:false,revision});}
 let all=[];for(let offset=0;;offset+=500){const r=await sb.from(TABLE).select('*').order('id').range(offset,offset+499);if(r.error)throw r.error;all.push(...r.data);if(r.data.length<500)break;}
 for(const r of all){const local=docs.find(d=>d.id===r.id);if(local?.dirty)continue;await put({...r.metadata,id:r.id,revision:r.revision,dirty:false,pdf:local?.pdf});}el('prodCloudStatus').textContent='Cloud gesynchroniseerd als '+account.email+'. Originele PDF’s zijn privé.';draw();}
 async function blobFor(d){if(d.pdf)return d.pdf;if(!sb)throw Error('Log in om de originele bon op te halen.');const r=await sb.storage.from(BUCKET).download(d.id+'.pdf');if(r.error)throw r.error;await put({...d,pdf:r.data});return r.data;}
 function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}
 async function run(fn){try{await fn();}catch(e){status('Niet voltooid: '+e.message);el('prodCloudStatus').textContent=account?'Cloud niet gesynchroniseerd; lokale wijzigingen blijven bewaard.':'';}}
 el('prodImport').onclick=()=>el('prodFiles').click();el('prodFiles').onchange=()=>run(async()=>{if(busy)return;busy=true;try{for(const f of el('prodFiles').files)await archive(f);if(account)await sync();}finally{busy=false;el('prodFiles').value='';}});
 // Existing revenue import: archive before parsing; a repeated filename never creates revenue copies.
 const oldHandle=handleFiles;handleFiles=async function(files){if(busy){status('Er loopt al een import. Wacht tot deze klaar is.');return;}busy=true;try{for(const f of files){try{const fresh=await archive(f);if(fresh&&!rows.some(r=>r.bestand===f.name))await oldHandle([f]);else if(fresh)log('Bestaande omzet behouden; bon toegevoegd aan archief: '+f.name);}catch(e){status('Bon niet bewaard: '+f.name+' — '+e.message);}}if(account)await sync();}finally{busy=false;}};
 section.addEventListener('click',e=>{const b=e.target.closest('[data-prod-edit]');if(b)edit(b.dataset.prodEdit);const r=e.target.closest('[data-prod-remove]');if(r){active.items.splice(+r.dataset.prodRemove,1);itemsDraw();}});
 section.addEventListener('input',e=>{const t=e.target;if(t.dataset.pi!==undefined){active.items[+t.dataset.pi][t.dataset.pk]=t.value;if(t.dataset.pk==='kind'&&C.kinds[t.value]){active.items[+t.dataset.pi].unit=C.kinds[t.value];t.closest('tr').querySelector('select').value=C.kinds[t.value];}}});
 el('prodAdd').onclick=()=>{active.items.push(empty());itemsDraw();};el('prodDraft').onclick=()=>run(()=>save(false));el('prodConfirm').onclick=()=>run(()=>save(true));el('prodExclude').onclick=()=>run(()=>save(false,true));el('prodClose').onclick=()=>{if(confirm('Editor sluiten? Niet opgeslagen wijzigingen gaan verloren.')){active=null;el('prodEditor').hidden=true;}};
 el('prodOpen').onclick=()=>run(async()=>download(await blobFor(active),active.name));el('prodYear').onchange=draw;el('prodClient').onchange=draw;
 el('prodLogin').onclick=()=>run(async()=>{if(!sb)throw Error('Cloud nog niet beschikbaar.');const r=await sb.auth.signInWithPassword({email:el('prodEmail').value.trim(),password:el('prodPassword').value});el('prodPassword').value='';if(r.error)throw r.error;account=r.data.user;await sync();});el('prodSync').onclick=()=>run(sync);el('prodLogout').onclick=()=>run(async()=>{if(sb)await sb.auth.signOut();account=null;el('prodCloudStatus').textContent='Uitgelogd. Het lokale archief blijft op dit apparaat beschikbaar.';});
 el('prodExport').onclick=()=>{const year=String(el('prodYear').value),client=el('prodClient').value,data=docs.filter(d=>!d.excluded&&d.confirmed&&!C.errors(d).length).flatMap(d=>d.items.filter(x=>x.date.slice(0,4)===year&&(!client||x.client===client)).map(x=>({'Uitvoeringsdatum':x.date,'Klant':x.client,'Project':x.project,'Soort':x.kind,'Aantal':C.number(x.quantity),'Eenheid':x.unit,'Bon':d.name,'Bronregel':x.source})));if(!data.length){status('Geen gecontroleerde aantallen in deze selectie.');return;}const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(data),'Productie');XLSX.writeFile(w,'productie-'+year+'.xlsx');};
 el('prodBackup').onclick=()=>run(async()=>{status('Back-up maken; bij veel bonnen kan dit even duren.');const data=[];for(const d of docs){const b=await blobFor(d),base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(b);});data.push({...meta(d),base64});}download(new Blob([JSON.stringify({format:'gr-bonnen-v1',docs:data})],{type:'application/json'}),'bonarchief-'+new Date().toISOString().slice(0,10)+'.json');status('Back-up gedownload, inclusief originele PDF’s. Bewaar deze op een veilige plek.');});
 el('prodRestore').onclick=()=>el('prodRestoreFile').click();el('prodRestoreFile').onchange=()=>run(async()=>{const f=el('prodRestoreFile').files[0];if(!f)return;const data=JSON.parse(await f.text());if(data.format!=='gr-bonnen-v1'||!Array.isArray(data.docs))throw Error('Ongeldig back-upbestand');for(const r of data.docs){if(docs.some(d=>d.id===r.id))continue;const bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0));if(await hash(bytes)!==r.id)throw Error('Bestandscontrole mislukt: '+r.name);const {base64,...d}=r;if(!Array.isArray(d.items)||!Array.isArray(d.pages))throw Error('Ongeldige bongegevens');await put({...d,pdf:new Blob([bytes],{type:'application/pdf'}),dirty:true,revision:0});}draw();status('Ontbrekende bonnen lokaal hersteld. Bestaande bonnen niet overschreven.');});
 const loaded=db('readonly',s=>s.getAll()).then(d=>{docs=d;draw();status('Bonarchief geladen. '+docs.length+' bonnen op dit apparaat.');}).catch(e=>status('Lokale opslag niet beschikbaar: '+e.message));
})();
