(function(root){
 'use strict';
 const kinds={'Boormeters':'m','Peilbuizen geplaatst':'st','Straatpotten gebruikt':'st'};
 function number(v){if(typeof v==='number')return v;let s=String(v??'').trim();if(!/^-?\d+(?:[.,]\d+)*$/.test(s))return NaN;if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if(/^-?\d{1,3}(\.\d{3})+$/.test(s))s=s.replace(/\./g,'');return Number(s);}
 function validDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return false;const d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s;}
 function errors(doc){const a=[];if(!doc.executed)a.push('Bevestig dat het uitgevoerd werk betreft, geen offerte of order.');if(!doc.items.length)a.push('Voeg minstens Ã©Ã©n hoeveelheid toe.');doc.items.forEach((x,i)=>{const p='Regel '+(i+1)+': ';if(!validDate(x.date))a.push(p+'vul een geldige uitvoeringsdatum in.');if(!String(x.project||'').trim()||!String(x.client||'').trim())a.push(p+'project en klant zijn verplicht.');if(!x.kind||!['m','st','kg','uur','m3'].includes(x.unit))a.push(p+'kies soort en eenheid.');if(kinds[x.kind]&&kinds[x.kind]!==x.unit)a.push(p+'onjuiste eenheid voor deze soort.');if(!Number.isFinite(number(x.quantity)))a.push(p+'vul een geldig aantal in.');if(x.unit==='st'&&!Number.isInteger(number(x.quantity)))a.push(p+'stuks moeten gehele aantallen zijn.');});return a;}
 function totals(docs,year,client=''){const sums={};let checked=0,pending=0;for(const d of docs){if(d.excluded)continue;if(!d.confirmed||errors(d).length){pending++;continue;}checked++;for(const x of d.items){if(x.date.slice(0,4)!==String(year)||client&&x.client!==client)continue;const key=x.kind+'|'+x.unit;sums[key]=(sums[key]||0)+number(x.quantity);}}return {sums,checked,pending};}
 function suggestions(pages){let project='';const out=[];for(let p=0;p<pages.length;p++){for(const line of pages[p].split('\n')){const pm=line.match(/Project(?:nummer|code)?\s*:?\s*(\S+)/i);if(pm)project=pm[1];let kind='';if(/straatpot/i.test(line))kind='Straatpotten gebruikt';else if(/peilbui[sz]/i.test(line)&&!/bemonster|watermonster|afpompen|verwijder|diameter|filterbuis|stijgbuis/i.test(line))kind='Peilbuizen geplaatst';else if(/boren|boormeters|boring/i.test(line)&&!/diameter|diepte|transport|aanvoer/i.test(line))kind='Boormeters';if(!kind)continue;const unit=kinds[kind];const re=unit==='m'?/(-?\d+(?:[.,]\d+)*)\s*(?:m(?:eter)?\b)/gi:/(-?\d+(?:[.,]\d+)*)\s*(?:st(?:uk(?:s)?)?\.?\b)/gi;const matches=[...line.matchAll(re)];out.push({project,client:'',date:'',kind,unit,quantity:matches.length===1?String(number(matches[0][1])):'',source:'Pagina '+(p+1)+': '+line.trim()});}}return out;}
 const api={kinds,number,validDate,errors,totals,suggestions};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ProductionCore=api;
})(typeof window==='undefined'?globalThis:window);
